[package]
name = "spotify-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "spotify"
path = "src/main.rs"

[dependencies]
echo-core = { workspace = true }

anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }

[package.metadata.packager]
product-name = "Echo TUI"
identifier = "com.echo.tui"
publisher = "Echo"
category = "Music"
icons = [
    "../../icons/icon.icns",
    "../../icons/icon.ico",
    "../../icons/32x32.png",
    "../../icons/128x128.png",
    "../../icons/icon.png",
    "../../icons/128x128@2x.png",
]
resources = [
    { src = "../../themes", target = "themes" },
    { src = "../../assets/install.sh", target = "install.sh" },
    { src = "../../assets/spotify.desktop", target = "spotify.desktop" },
    { src = "../../assets/echo-rs.svg", target = "echo.svg" },
]
before-packaging-command = "cargo build --release -p spotify-tui"

[package.metadata.packager.deb]
desktop_template = "../../assets/spotify.desktop.hbs"
depends = ["libssl3", "libasound2", "libdbus-1-3"]
