primary = "#3e745d"
secondary = "#528e74"
background = "#d5e2d8"
surface = "#e7f0ea" # menus, modals, popovers
text = "#3f5c4f"
text_muted = "#849e8f"
highlight_bg = "#517b68"
highlight_fg = "#e7f3eb"
error = "#ca4032"
