primary = "#a47838"
secondary = "#ac8341"
background = "#ecead9"
surface = "#f7f5e9" # menus, modals, popovers
text = "#70624e"
text_muted = "#88795e"
highlight_bg = "#a48b4f"
highlight_fg = "#3a3227"
error = "#a8423e"
