use crate::models::{PlaybackItem, Playlist, SearchResults, Track};
use crossterm::event::KeyEvent;

pub enum AppEvent {
    Key(KeyEvent),
    LoadContextTracks(String, bool, Option<String>, Option<(String, String, String, String)>),
    PlayTrack {
        context_id: String,
        track_id: String,
        is_album: bool,
        title: String,
        artist: String,
        duration_ms: u32,
        image_url: Option<String>,
        album_id: Option<String>,
    },
    StartAuth,
    Quit,
    TogglePlayback(bool),
    NextTrack {
        current_track_id: Option<String>,
    },
    PreviousTrack {
        current_track_id: Option<String>,
    },
    ToggleShuffle(bool),
    SetRepeatMode(String),
    SetVolume(u8),
    LoadTrackMetadata(String),
    GlobalSearch(String),
    AddToQueue(Vec<String>),
    FetchQueue,
    AddTracksToPlaylist(String, Vec<String>),
    RemoveTracksFromPlaylist(String, Vec<String>),
    CreatePlaylist(String),
    RenamePlaylist(String, String),
    DeletePlaylists(Vec<String>),
    DeletePlaylistTracks(String, Vec<String>),
    SaveAlbums(Vec<String>),
    RemoveAlbums(Vec<String>),
    ToggleTrackLike(String, bool),
    ReloadHeaderImage,
}

pub enum WorkerEvent {
    Tick,
    AuthenticationComplete,
    UserIdentityLoaded(String),
    PlaylistsLoaded(Vec<Playlist>),
    AlbumsLoaded(Vec<crate::models::Album>),
    TracksLoaded(Vec<Track>, Option<(String, String, String, String)>),
    AudioVisualizationReady(std::sync::Arc<parking_lot::Mutex<[f32; 32]>>, std::sync::Arc<std::sync::atomic::AtomicBool>),
    PlaybackStarted {
        item: PlaybackItem,
    },
    SyncPlaybackState {
        is_playing: bool,
        is_shuffled: bool,
        repeat_mode: String,
        volume: Option<u32>,
        device_name: String,
        progress_ms: u32,
        item: Option<PlaybackItem>,
    },
    ForceRedraw,
    ForceContextRefresh,
    TrackMetadataLoaded {
        track_id: String,
        title: String,
        artist: String,
        image_url: Option<String>,
    },
    TrackImageProcessed {
        track_id: String,
        protocol: ratatui_image::protocol::StatefulProtocol,
    },
    SearchResultsLoaded(SearchResults),
    QueueLoaded(Vec<Track>),
    TracksQueued(usize),
    HeaderImageProcessed(ratatui_image::protocol::StatefulProtocol),
    LikedStatusUpdate(std::collections::HashMap<String, bool>),
}
